# download.yaml
---
- name: Download and archive backup folder
  hosts: all
  become: true

  vars:
    backup_folder_path: "/home/{{ ansible_user }}/backups"
    local_download_path: "/tmp/downloads/{{ ansible_hostname }}/"

  tasks:
    - name: Archive the backup folder
      archive:
        path: "{{ backup_folder_path }}"
        dest: "/tmp/backup_{{ ansible_date_time.iso8601_basic_short }}.tar.gz"
        format: gz
      become: yes

    - name: Fetch the archived backup from remote host
      fetch:
        src: "/tmp/backup_{{ ansible_date_time.iso8601_basic_short }}.tar.gz"
        dest: "{{ local_download_path }}"
        flat: yes
      timeout: 3600  # Set the timeout to 1 hour (in seconds)

    - name: Remove temporary archive on the remote server
      file:
        path: "/tmp/backup_{{ ansible_date_time.iso8601_basic_short }}.tar.gz"
        state: absent
      become: yes
